version: '3.8'
services:
  book_catalog:
    build:
      context: ./book_catalog/
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://manjinder_sit722_week7_gb2g_user:CsBzvkyNMvrTk7MTLcpRXFKZFodpX8Pf@dpg-crg0743qf0us73de0ep0-a.oregon-postgres.render.com/manjinder_sit722_week7_gb2g

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://manjinder_sit722_week7_gb2g_user:CsBzvkyNMvrTk7MTLcpRXFKZFodpX8Pf@dpg-crg0743qf0us73de0ep0-a.oregon-postgres.render.com/manjinder_sit722_week7_gb2g
